# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: cinic10
val_db_name: cinic10
num_classes: 10
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.47889522, 0.47227842, 0.43047404]
      std: [0.24205776, 0.23828046, 0.25874835]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.47889522, 0.47227842, 0.43047404]
      std: [0.24205776, 0.23828046, 0.25874835]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 512
val_batch_size: 512
num_workers: 8

# Scheduler
scheduler: constant
